[project]
name = "v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "protobuf>=5.29.3",
    "pyelftools>=0.31",
    "west>=1.3.0",
]
